import numpy as np
ls = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(ls.shape)

In [32]:
import numpy as np 
from math import e
from math import log

mat = np.array([[0,1,2],[1,-3,3],[3,6,1],[-5,6,-4]])
print(mat)

results = {}
best_val = -1
best_net = None
best_params = ()
learning_rates = [4e-4,6e-4,8e-4,1e-3,2e-3]
reg_strengths = [0.3,0.6,0.7,0.9]

hidden_size=75

for i in learning_rates:
    for j in  reg_strengths:
        

[[ 0  1  2]
 [ 1 -3  3]
 [ 3  6  1]
 [-5  6 -4]]
training for lr and reg =  0.0004    0.3
training for lr and reg =  0.0004    0.6
training for lr and reg =  0.0004    0.7
training for lr and reg =  0.0004    0.9
training for lr and reg =  0.0006    0.3
training for lr and reg =  0.0006    0.6
training for lr and reg =  0.0006    0.7
training for lr and reg =  0.0006    0.9
training for lr and reg =  0.0008    0.3
training for lr and reg =  0.0008    0.6
training for lr and reg =  0.0008    0.7
training for lr and reg =  0.0008    0.9
training for lr and reg =  0.001    0.3
training for lr and reg =  0.001    0.6
training for lr and reg =  0.001    0.7
training for lr and reg =  0.001    0.9
training for lr and reg =  0.002    0.3
training for lr and reg =  0.002    0.6
training for lr and reg =  0.002    0.7
training for lr and reg =  0.002    0.9


In [89]:
sample = np.random.choice(train,20,replace=False)
# print(sample)
sample = sample.reshape(5,2,2)
# print(sample.shape)
sample = sample.reshape(sample.shape[0],-1)
# print(sample.shape)
# print(sample)
# mean = np.mean(sample,axis=0)
# std = np.std(sample,axis=0)
# print(mean)
# print(sample-mean)
print(sample)
mqq = np.ones((sample.shape[0],1))
print([sample,mqq])
# sample = np.hstack((sample,np.ones(sample.shape[0],1)))
# pri11nt(sample)

[[ 61  58  52  97]
 [ 16  25  85  79]
 [118  43  55 112]
 [ 13  73 115  49]
 [ 67 109  76  91]]
[array([[ 61,  58,  52,  97],
       [ 16,  25,  85,  79],
       [118,  43,  55, 112],
       [ 13,  73, 115,  49],
       [ 67, 109,  76,  91]]), array([[ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.]])]


In [115]:
# print(4-53.2)
one = np.ones((sample.shape[0],1))
t = np.concatenate((one,sample),axis=1)
print( np.random.randn(3073, 10)*0.001)

[[ -2.54396064e-04  -1.61272359e-03  -1.48254892e-03 ...,   8.41606376e-05
   -3.67268486e-04   1.75608078e-04]
 [ -4.51229602e-04  -3.18654094e-04  -5.77864328e-04 ...,   9.99037463e-04
   -1.30208443e-03   3.34761799e-05]
 [ -6.13308761e-04   1.04421079e-03   8.94569721e-05 ...,   1.89694916e-03
   -1.33806130e-03   1.18264593e-03]
 ..., 
 [  1.24949226e-03   7.93932305e-04   1.37134677e-03 ...,   1.64930196e-03
   -5.98762386e-04   1.72292540e-04]
 [ -7.08806118e-04  -3.37157759e-04  -3.42831128e-04 ...,   5.45272841e-04
   -1.38977058e-03  -3.64155527e-04]
 [ -1.10139254e-03   1.57393843e-03  -1.63796939e-04 ...,  -7.53215608e-04
    8.05750130e-04   1.29265845e-03]]


In [171]:
x = np.arange(20)
scores = x.reshape(4,5)
print(scores)
y = np.array([1,0,3,2])
# y = np.reshape(y,(y.shape[0],1))
print(y)

scores = scores - (scores[np.arange(4),y]).reshape(4,1)+1
print(scores)
scores = np.maximum(scores,np.zeros(scores.shape))
print(scores)
scores[np.arange(4),y]=0
print(scores)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[1 0 3 2]
[[ 0  1  2  3  4]
 [ 1  2  3  4  5]
 [-2 -1  0  1  2]
 [-1  0  1  2  3]]
[[ 0.  1.  2.  3.  4.]
 [ 1.  2.  3.  4.  5.]
 [ 0.  0.  0.  1.  2.]
 [ 0.  0.  1.  2.  3.]]
[[ 0.  0.  2.  3.  4.]
 [ 0.  2.  3.  4.  5.]
 [ 0.  0.  0.  0.  2.]
 [ 0.  0.  0.  2.  3.]]


In [151]:
x = np.array([[1, 2], [3, 4], [5, 6]])
print(x)
print(x[[0, 1, 2], [0, 1, 0]])

[[1 2]
 [3 4]
 [5 6]]
[1 4 5]


In [20]:
mat = np.array([[0,5,3,0,0],[5,0,0,0,1],[6,5,0,23,1],[5,4,3,0,1]])
print(mat)
print(x)
y = [1,20]
d={}
m=1
a=9
b=8
n=2
d[(a,b)] = (m,n)
print(d[(a,b)])


[[ 0  5  3  0  0]
 [ 5  0  0  0  1]
 [ 6  5  0 23  1]
 [ 5  4  3  0  1]]
[1 0 3 0]
(1, 2)


37


45
