In [140]:
import numpy as np

mat1 = np.arange(1,30,2)
mat2 = np.arange(9)
mat1 = np.reshape(mat1,(5,3))
mat2 = np.reshape(mat2,(3,3))
'''
print(mat1)
print('**************')
print(mat2)
print('*****************')
print(sum(((mat1[0]-mat2[0])**2)))

'''
dist = np.zeros((3,5))
'''
print('*******************')
'''
for i in range(3):
    for j in range(5):
        #print('i= %d and j= %d are '%(i,j))
        dist[i][j] = math.sqrt(sum((mat2[i]-mat1[j])**2)) 
        #print('for %d and %d layer is '%(i,j) , (mat2[i]-mat1[j])**2)
print('***********************0')
print(dist.shape)
print(dist)

new = np.zeros((3,5))
for i in range(3):
    new[i:] = np.sqrt(np.sum((mat2[i]-mat1)**2,axis=1))
print('**************0')
print(new)
print('**************0')
t1 = (mat2**2).sum(axis=1,keepdims=True)
t2 = (mat1**1).sum(axis=1)
t3 = 2*(mat2.dot(mat1.T))
print(t1.shape)
print(t2.shape)
t = t1+t2
print(t.shape)
print(t3.shape)
print(t)
print(t3)
trr = t-t3
print(trr.shape)
new = np.sqrt((mat2**2).sum(axis=1,keepdims=True)+(mat1**2).sum(axis=1)-2*(mat2.dot(mat1.T)))
print(new)

***********************0
(3, 5)
[[  3.74165739  13.92838828  24.2899156   34.66987165  45.0555213 ]
 [  2.23606798   8.77496439  19.10497317  29.47880595  39.86226286]
 [  7.07106781   3.74165739  13.92838828  24.2899156   34.66987165]]
**************0
[[  3.74165739  13.92838828  24.2899156   34.66987165  45.0555213 ]
 [  2.23606798   8.77496439  19.10497317  29.47880595  39.86226286]
 [  7.07106781   3.74165739  13.92838828  24.2899156   34.66987165]]
**************0
(3, 1)
(5,)
(3, 5)
(3, 5)
[[ 14  32  50  68  86]
 [ 59  77  95 113 131]
 [158 176 194 212 230]]
[[  26   62   98  134  170]
 [  80  224  368  512  656]
 [ 134  386  638  890 1142]]
(3, 5)
[[  3.74165739  13.92838828  24.2899156   34.66987165  45.0555213 ]
 [  2.23606798   8.77496439  19.10497317  29.47880595  39.86226286]
 [  7.07106781   3.74165739  13.92838828  24.2899156   34.66987165]]


In [136]:
print(mat1)
print(mat2)
print(np.sqrt(mat1))
#new = (mat1**2).sum(axis=1,keepdims=True)+(mat2**2).sum(axis=1)
#print(new)
f = (mat2**2).sum(axis=1,keepdims=True)
s = (mat1**2).sum(axis=1)
print(f)
print(s)
print(f+s)

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]
 [19 21 23]
 [25 27 29]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 1.          1.73205081  2.23606798]
 [ 2.64575131  3.          3.31662479]
 [ 3.60555128  3.87298335  4.12310563]
 [ 4.35889894  4.58257569  4.79583152]
 [ 5.          5.19615242  5.38516481]]
[[  5]
 [ 50]
 [149]]
[  35  251  683 1331 2195]
[[  40  256  688 1336 2200]
 [  85  301  733 1381 2245]
 [ 184  400  832 1480 2344]]


In [176]:
a = [1,2,3,4,5,6]
b = [5,2,6,4,9,7]
a = np.array(a)
b = np.array(b)
print(np.sum(a==b))
print(len(a))

2
6
